version: "3.3"
services:
  java:
    image: speaking-snail
    container_name: speaking-snail
    ports:
      - 8080:8080
    tty: true
  db:
    image: snail-db
    container_name: snail-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8081:8080
